SAMPLE_LIST : "bl6_bam_name.txt"
STRAIN : "bl6"
VARIANTS : "/hps/nobackup2/flicek/user/cander21/lce20191105/geno/bl6.projectedFilteredMu.tab"
PATH_TO_BAM : "/nfs/leia/research/flicek/user/fnc-odompipe/lce-collaboration/repository/merged_alignments/alignments_20171018/"
GENOME : "/nfs/leia/research/flicek/user/fnc-odompipe/lce-collaboration/genome_metadata/genomes/mus_musculus/GRCm38_S288C/GRCm38_S288C.fa"
PATH_TO_FNOD : "/hps/nobackup2/flicek/user/mst/lce/nodules"
PATH_TO_DRCR : "/hps/nobackup2/flicek/user/mst/lce/nodules"
